#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_0_IS_DUAL 0x0
#define XPAR_AXI_GPIO_0_INTERRUPTS 0x2000
#define XPAR_FABRIC_AXI_GPIO_0_INTR 0
#define XPAR_AXI_GPIO_0_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x20

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_FABRIC_XGPIO_0_INTR 0
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x20
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x0
#define XPAR_XGPIO_0_INTERRUPTS 0x2000
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_IIC_0 */
#define XPAR_AXI_IIC_0_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000
#define XPAR_AXI_IIC_0_HIGHADDR 0x4080ffff
#define XPAR_AXI_IIC_0_TEN_BIT_ADR 0x0
#define XPAR_AXI_IIC_0_GPO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_IIC_0 */
#define XPAR_XIIC_0_BASEADDR 0x40800000
#define XPAR_XIIC_0_HIGHADDR 0x4080ffff
#define XPAR_XIIC_0_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_XIIC_0_GPO_WIDTH 0x1
#define XPAR_XIIC_0_TEN_BIT_ADR 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0xe
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x5
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HANDLER_TABLE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_SW_INTR 0x0

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0xe
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x5
#define XPAR_XINTC_0_NUM_SW_INTR 0x0
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a00000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a0ffff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x0
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x10
#define XPAR_AXI_QUAD_SPI_0_INTERRUPTS 0x1
#define XPAR_FABRIC_AXI_QUAD_SPI_0_INTR 1
#define XPAR_AXI_QUAD_SPI_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a00000
#define XPAR_FABRIC_XSPI_0_INTR 1
#define XPAR_XSPI_0_HIGHADDR 0x44a0ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x10
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_INTERRUPTS 0x1
#define XPAR_XSPI_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x0
#define XPAR_XSPI_0_STARTUP_BLOCK 0x0
#define XPAR_XSPI_0_XIP_MODE 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2004
#define XPAR_FABRIC_AXI_TIMER_0_INTR 4
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_0_INTR 4
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2004
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x3
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 3
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_0_INTR 3
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x3
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral PMODSD_0 */
#define XPAR_PMODSD_0_BASEADDR 0x44a10000
#define XPAR_PMODSD_0_HIGHADDR 0x44a1ffff

/* Canonical definitions for peripheral PMODSD_0 */
#define XPAR_PMODSD_0_BASEADDR 0x44a10000
#define XPAR_PMODSD_0_HIGHADDR 0x44a1ffff

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x7fff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_FPU 1
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */